# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
$:.unshift("~/.rubymotion/rubymotion-templates")
require 'motion/project/template/tvos'

begin
  require 'bundler'
  Bundler.require
rescue LoadError
end

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'WeatherTV'
  app.fonts = ['Climacons.ttf']
  app.frameworks += %w(CoreLocation)
  app.detect_dependencies = true
  app.pods do
    pod 'CZWeatherKit'
  end
end
